name: Publish Package to npm
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci

      - id: publish-to-npm
        uses: JS-DevTools/npm-publish@v1
        with:
          greater-version-only: true
          registry: 'https://registry.npmjs.org'
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish-to-npm.outputs.type != 'none'
        run: |
          echo "Version changed in NPM: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"

      - id: publish-to-gh
        uses: JS-DevTools/npm-publish@v1
        with:
          greater-version-only: true
          registry: 'https://npm.pkg.github.com'
          token: ${{ secrets.GH_PKG_TOKEN }}
      - if: steps.publish-to-gh.outputs.type != 'none'
        run: |
          echo "Version changed in GH: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
